version: '3.9'

services:
  mysql:
    image: arm64v8/mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: irino
      MYSQL_DATABASE: inventra
      MYSQL_USER: inventra
      MYSQL_PASSWORD: "@Inventra123"
    ports:
      - "3406:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8888:80"

  ml_service:
    build: ../ml_service
    container_name: ml_service
    restart: always
    depends_on:
      - mysql
    environment:
      - ML_DB_HOST=mysql
      - ML_DB_USER=inventra
      - ML_DB_PASS=@Inventra123
      - ML_DB_NAME=inventra
    ports:
      - "5000:5000"

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - mysql
      - ml_service
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=irino
      - DB_NAME=inventra
      - RESEND_API_KEY=re_29KHLZqH_9eEuBgEVfnKXqi5pWoEM6r98
      - ML_SERVICE_URL=http://ml_service:5000/forecast
      - FORECAST_PRODUCT_SKU=TOTAL_SALES_PLACEHOLDER
    ports:
      - "4000:4000"
    volumes:
      - .:/app 

# ðŸ”’ Define persistent named volume for MySQL
volumes:
  mysql_data:
    driver: local
