
services:
  mysql:
    image: arm64v8/mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: irino
      MYSQL_DATABASE: inventra
    ports:
      - "3406:3306"
    volumes:
      - ../mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8888:80"

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: inventra
      DB_PASS: "@Inventra123"
      DB_NAME: inventra
      RESEND_API_KEY: "re_29KHLZqH_9eEuBgEVfnKXqi5pWoEM6r98"
    ports:
      - "4000:4000"